sudo: required
services:
  - docker

before_install:
  - docker-compose -f docker-compose-test.yml up

script:
  - docker-compose -f docker-compose-test.yml run api npm test
<<<<<<< HEAD
  - docker-compose -f docker-compose-test.yml down
=======
>>>>>>> f14310192008e84375227b51fb4ab71ff2f08ef9

deploy:
  provider: heroku
  app: "api-felicidade"
  api_key:
    secure: "$HEROKU_API_KEY"
  on:
    branch: master
