sudo: required
services:
  - docker

before_install:
  - docker-compose -f docker-compose-test.yml up --build -d

script:
  - docker-compose exec api-felicidade_api npm test

after_script:
  - docker-compose down

deploy:
  provider: heroku
  app: "api-felicidade"
  api_key:
    secure: "$HEROKU_API_KEY"
  on:
    branch: master
