sudo: required
services:
  - docker

before_install:
  - docker-compose up

script:
  - docker run api npm test

deploy:
  provider: heroku
  app: "api-felicidade"
  api_key:
    secure: "$HEROKU_API_KEY"
  on:
    branch: master
