sudo: required

services:
  - docker

env:
  - CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN

before_install:
  - docker-compose -f tests.yml up -d

script:
  - docker-compose -f tests.yml run -e CODACY_PROJECT_TOKEN api npm run test-with-coverage

after_script:
  - docker-compose down

deploy:
  provider: heroku
  app: "api-felicidade"
  api_key:
    secure: "$HEROKU_API_KEY"
  on:
    branch: master
