sudo: required

language: node_js

node_js:
  - 12

services:
  - docker

before_install:
  - docker-compose -f tests.yml up -d

script:
  - docker-compose -f tests.yml run api npm test-with-coverage

after_script:
  - docker-compose down

deploy:
  provider: heroku
  app: "api-felicidade"
  api_key:
    secure: "$HEROKU_API_KEY"
  on:
    branch: master
