version: "2.4"
services:
  api:
    build:
      context: .
      target: dev
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: "mongo:4.2.1"
    ports:
      - 27017:27017
    restart: always

  seed:
    build: ./seed
    depends_on:
      - mongo
