version: "2.4"
services:
  api:
    build:
      context: .
      target: test
    environment:
      - NODE_ENV=test
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: "mongo"
    ports:
      - 27017:27017
    restart: always

  seed:
    build: ./seed
    depends_on:
      - mongo
