version: "2.4"
services:
  api:
    build:
      context: .
      target: test
    environment:
      - NODE_ENV=test
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: "mongo:4.2.1"
    restart: always
