name: CI

on: [push]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - name: Rise up the container
       run: docker-compose -f tests.yml up -d --build
     - name: Run the tests
       run: docker-compose -f tests.yml run -e CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }} api npm run test-with-coverage

